### ISSUE TITLE
Forget password not working?

### ISSUE THREAD

**Issue by JayyDoesDev** [D-Clone/Website#18]
It seems as though forget password doesn't actually work with the email you signed up with during dclone. For example as my self I forget the pass and so I typed in the email and it said the email was sent but wasn't. Which also means I am stuck locked out of my account at the same time.

**Comment by theADAMJR** [comment]
This could have been due to the bug yesterday. What is your username and discriminator?

**Comment by theADAMJR** [comment]
https://d-cl.one was just a simple demo and was not intended to be compatible accord.
Accord.app data from May-July (v1), were migrated, but d-cl.one data was not.

**Comment by JayyDoesDev** [comment]
The username is J_DDev and discrim 0001

**Comment by colderryboy** [comment]
![image](https://user-images.githubusercontent.com/72723052/134779775-e0abf63a-cb2c-46b4-b7fb-3504cf873a0f.png)

**Comment by theADAMJR** [comment]
This seems to be from a previous accord v1 'intentional bug' where emails were set to `177131649555841025@avoid-mongodb-error.com`, because they didn't verify their email. Nobody has a chance of guessing that though, so maybe I'll have to set their email manually. Try `<username>-<discriminator>@example.com` because I have changed this manually.

**Comment by theADAMJR** [comment]
All accounts with this email convention from accord v1, have now been updated to `<username>-<discriminator>@example.com`.
