### ISSUE TITLE
All your code is a bug, literally all of it[BUG]

### ISSUE THREAD

**Issue by JuilawasFlagged** [D-Clone/Website#29]
**Describe the bug**
Literally, exploits out of the ass, its honestly sad.

**To Reproduce**
Just use Accord. Thats how you do it.

**Expected behavior**
be a subpart discord clone

**Screenshots**

**Desktop (please complete the following information):**
 All versions.
**Smartphone (please complete the following information):**
Java Phone/Flipphone
**Additional context**

**Comment by JuilawasFlagged** [comment]
Oh yeah, not to mention, your service was wrecked.

**Comment by ghost** [comment]
learn how to code :trollface:

**Comment by JuilawasFlagged** [comment]
yes

**Comment by JuilawasFlagged** [comment]
![image](https://user-images.githubusercontent.com/92193825/136660672-d498cf67-e7b3-46e5-b485-e057adf56808.png)

**Comment by DavidCavallaro** [comment]
> **Describe the bug** Literally, exploits out of the ass, its honestly sad.
> 
> **To Reproduce** Just use Accord. Thats how you do it.
> 
> **Expected behavior** be a subpart discord clone
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):** All versions. **Smartphone (please complete the following information):** Java Phone/Flipphone **Additional context** Add any other context about the problem here.

what would be the problem?

**Comment by ghost** [comment]
> > **Describe the bug** Literally, exploits out of the ass, its honestly sad.
> > **To Reproduce** Just use Accord. Thats how you do it.
> > **Expected behavior** be a subpart discord clone
> > **Screenshots** If applicable, add screenshots to help explain your problem.
> > **Desktop (please complete the following information):** All versions. **Smartphone (please complete the following information):** Java Phone/Flipphone **Additional context** Add any other context about the problem here.
> 
> what would be the problem?

literally everything

**Comment by JuilawasFlagged** [comment]
> > **Describe the bug** Literally, exploits out of the ass, its honestly sad.
> > **To Reproduce** Just use Accord. Thats how you do it.
> > **Expected behavior** be a subpart discord clone
> > **Screenshots** If applicable, add screenshots to help explain your problem.
> > **Desktop (please complete the following information):** All versions. **Smartphone (please complete the following information):** Java Phone/Flipphone **Additional context** Add any other context about the problem here.
> 
> what would be the problem?

Literally everything, your service has been sent to the shadow realm.

**Comment by theADAMJR** [comment]
The problem was that the 256 bit secret for signing and verifying JWT's was literally hard coded as `'secret'`. I didn't realize this until now. It has been [replaced with RSA256](https://github.com/accord-dot-app/app/commit/8b50edd197a79c444a171a0ff2a055a9d3c18c70#diff-8d93bfa6323ab98e050408785438e43821b1905533ce7439f1b85da958b44a7dL59) keys that have to be manually generated when setting up this project. This code was from the first version of the API, and there would not be an exploit if [DClone's API](https://github.com/codea-live/dclone/blob/essential/backend/src/rest/routes/auth-routes.ts#L35) was used as a foundation for v2.

One disadvantage with a source-available model is that code is easier to exploit, but patches can be made earlier and less damage can be done, if we're dealing with responsible human beings - not all are.
